# Generated by Django 3.1.6 on 2021-03-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_auto_20210309_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partneraddress',
            name='line2',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
