# Generated by Django 3.1.6 on 2021-04-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20210326_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='last_name',
            field=models.CharField(blank=True, help_text='para onde devemos entregar o seu pedido?', max_length=255, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='line1',
            field=models.CharField(help_text='Data que você deseja agendar', max_length=255, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='line2',
            field=models.CharField(blank=True, help_text='Horario que você deseja agendar.', max_length=255, verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='last_name',
            field=models.CharField(blank=True, help_text='para onde devemos entregar o seu pedido?', max_length=255, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='line1',
            field=models.CharField(help_text='Data que você deseja agendar', max_length=255, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='line2',
            field=models.CharField(blank=True, help_text='Horario que você deseja agendar.', max_length=255, verbose_name='Horario'),
        ),
    ]
